name: reviewdog
on: [pull_request]

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: 'Build detekt'
        shell: bash
        run: ./gradlew detekt

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: 'Merge detekt reports'
        shell: bash
        run: |
          merged_report="merged_detekt.xml"
          echo '<?xml version="1.0" encoding="UTF-8"?>' > $merged_report
          echo '<checkstyle version="4.3">' >> $merged_report
          find . -name "detekt.xml" | while read -r file; do
            # Extract the content inside <checkstyle> tags
            grep -v '<?xml version="1.0" encoding="UTF-8"?>' "$file" | grep -v '<checkstyle version="4.3">' | grep -v '</checkstyle>' >> $merged_report
          done
          echo '</checkstyle>' >> $merged_report

      - name: 'Run reviewdog'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
        shell: bash
        run: |
          reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review" -level="info" < merged_detekt.xml
