name: Detekt Analysis
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run detekt
        run: ./gradlew detekt

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run reviewdog for all detekt reports
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
        shell: bash
        run: |
          detekt_files=$(find . -name "detekt.xml")
          for file in $detekt_files; do
            echo "Processing $file"
            base_dir=$(basename $(dirname $file))
            reviewdog_name="detekt-$base_dir"
            echo "Using reviewdog name: $reviewdog_name"
            cat "$file" | reviewdog -f=checkstyle -name="$reviewdog_name" -reporter="github-pr-review" -level="info"
          done
