name: reviewdog
on: [pull_request]

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: 'Build detekt'
        shell: bash
        run: ./gradlew detekt

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Merge detekt reports
        run: |
          merged_report="merged_detekt.xml"
          version=$(xmllint --xpath 'string(/checkstyle/@version)' $(find . -name "detekt.xml" | head -n 1))
          if [ -z "$version" ]; then
            version="4.3"
          fi
          echo '<?xml version="1.0" encoding="UTF-8"?>' > $merged_report
          echo "<checkstyle version=\"$version\">" >> $merged_report

          # Find all detekt.xml files and merge them into one report
          find . -name "detekt.xml" | while read -r file; do
            echo "Processing $file"
            # Append the content of each detekt.xml file except the header and footer
            xmllint --xpath '//file' "$file" >> $merged_report
          done

          echo '</checkstyle>' >> $merged_report
          cat $merged_report

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
        run: |
          cat merged_detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review" -level="info"
