name: reviewdog
on: [ pull_request ]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: 'build detekt'
        shell: bash
        run: ./gradlew detekt

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: "review dogs"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
        shell: bash
        run: |
          find . -name "detekt.xml" | while read -r file; do
            cat "$file" | reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review" -level="info"
          done
